name: KidsReporter
options:
  bundleIdPrefix: com.example
  developmentLanguage: en
  deploymentTarget:
    iOS: '17.0'

targets:
  KidsReporter:
    type: application
    platform: iOS
    deploymentTarget: '17.0'
    sources:
      - path: KidsReporter
        excludes:
          - 'Views' # Exclude the old Views folder since we copied files to main folder
    resources:
      - KidsReporter/Assets.xcassets
      - KidsReporter/Preview Content
    info:
      path: KidsReporter/Info.plist
      properties:
        CFBundleDisplayName: Kids Reporter
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: '1'
        CFBundleShortVersionString: '1.0'
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
        UILaunchScreen: {}
        NSCameraUsageDescription: 'This app needs camera access to record videos for reporting missions.'
        NSMicrophoneUsageDescription: 'This app needs microphone access to record audio for interviews and transcription.'
        NSSpeechRecognitionUsageDescription: 'This app uses speech recognition to automatically transcribe interviews.'
        NSPhotoLibraryUsageDescription: 'This app needs access to save and share reports via photos.'
    settings:
      base:
        TARGETED_DEVICE_FAMILY: '2' # iPad only
        SUPPORTS_MACCATALYST: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
